# TODO: Implementar el docker-compose.yml
version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: hangman-postgres
    restart: always
    environment:
      POSTGRES_DB: demobase
      POSTGRES_USER: demobase
      POSTGRES_PASSWORD: demobase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demobase"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - hangman-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hangman-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demobase
      SPRING_DATASOURCE_USERNAME: demobase
      SPRING_DATASOURCE_PASSWORD: demobase
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - hangman-network

volumes:
  postgres_data:

networks:
  hangman-network:
